/**:
  ros__parameters:
    device_path: ""           # Leave it blank for auto detection

    # USB 3.0
    # "8-bit Greyscale 1280 x 720 60 fps"
    # "8-bit Greyscale 1280 x 960 45 fps"
    # "8-bit Greyscale 320 x 240 160 fps"
    # "8-bit Greyscale 640 x 480 80 fps"
    #
    # USB 2.0
    # "8-bit Greyscale 1280 x 720 30 fps"
    # "8-bit Greyscale 1280 x 960 22.5 fps"
    # "8-bit Greyscale 320 x 240 160 fps"
    # "8-bit Greyscale 640 x 480 80 fps"
    Width: 640
    Height: 480
    FPS: 30

    Brightness: 110           # "Gain" (default [min, step, max]): 64 ( 64 [0, 1, 127])
    Exposure: 130             # "Exposure (Absolute)", (default [min, step, max]): 39 (39 [1, 1, 625])
    Auto exposure mode: 1     # 1 - Manual mode, 3 - Apeture priority mode
